### ISSUE TITLE
Option to choose supported versions for Red Hat Fuse

### ISSUE THREAD

**Issue by pittar** [mgubaidullin/kameleon#1]
It would be nice to have an option to select versions supported by Red Hat (Fuse) for people that have access to Red Hat Integration subscriptions.

Ideally, this would also reference the latest Fuse parent POMs/BOMs.

**Comment by mgubaidullin** [comment]
I would prefer to have a separate app for supported version to avoid users mislead. 
It might be also some legal issues from Red Hat side.
