### ISSUE TITLE
Grouped components cannot be selected

### ISSUE THREAD

**Issue by oscerd** [mgubaidullin/kameleon#2]
In 3.9.0 we grouped some components into middle folder: it is the case for aws, google and azure

If you try to select a component like aws-s3, you'll be able to select only the parent component, in this case camel-aws.

**Comment by mgubaidullin** [comment]
Thank.  
I get components list from Camel's repo on a github. 
It there better way to identify if there is a group of components that to check every folder?

**Comment by oscerd** [comment]
Probably it is worth to have a look at camel catalog jar

**Comment by mgubaidullin** [comment]
Fixed

**Comment by mgubaidullin** [comment]
Fixed
