### ISSUE TITLE
Switching between runtimes reset the camel version to the latest

### ISSUE THREAD

**Issue by oscerd** [mgubaidullin/kameleon#3]
it's not a bug, but it would be nice if while switching through runtimes the selected camel version would be maintained.

**Comment by mgubaidullin** [comment]
It could be done for spring, standalone and cdi because camel-quarkus has different versioning. will it work for you?

**Comment by oscerd** [comment]
Sure thing, it was just a suggestion to improve it a bit. nothing critical!

**Comment by mgubaidullin** [comment]
Fixed
