### ISSUE TITLE
Adding components from mobile device seems to do nothing.

### ISSUE THREAD

**Issue by ThePrez** [mgubaidullin/kameleon#5]
Just a nit. The `+` sign doesn't appear to do anything when I add on my mobile device. It does work, but the "selected components" section is rendered beneath the large list of components and easily missed. So, there's no feedback when adding a component and it appears to not be working. If visual feedback of some sort could be shown on screen, that would be great.

But then again, who is writing Camel code on their phone?

**Comment by mgubaidullin** [comment]
Fixed
